import type { Metadata } from 'next'

import SignInSignUpContent from '~/components/SignInSignUpContent'

export const metadata: Metadata = {
  title: 'The August Home - Login',
  description: 'Generated by create next app'
}

function SignInSignUp() {
  return <SignInSignUpContent />
}

export default SignInSignUp
