import type { Metadata } from 'next'

import Header from '~/components/Header'

export const metadata: Metadata = {
  title: 'The August Home',
  description: 'Generated by create next app'
}

export default function Home() {
  return (
    <div>
      <Header />
    </div>
  )
}
