import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

import { Providers as ThemeProviders } from '~/app/themeProviders'
import { Providers } from '~/redux/Provider'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'The August Home',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Providers>
      <html lang='en' suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProviders>{children}</ThemeProviders>
        </body>
      </html>
    </Providers>
  )
}
